site_name: EDISCRIPT Wiki
site_description: Komplexní dokumentace EDISCRIPT systému
site_author: lubman2
repo_url: https://github.com/lubman2/EDISCRIPT_Wiki
repo_name: EDISCRIPT_Wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: default
    primary: blue
    accent: blue

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist

nav:
  - Home: index.md
  - PCS skriptování:
    - Syntax guide: PCS/PCS_SYNTAX_GUIDE.md
    - Operace - referenční průvodce: PCS/PCS_OPERACE_REFERENCNI_PRUVODCE.md
  - COMDIS:
    - Kompletní průvodce: COMDIS/COMDIS_KOMPLETNI_PRUVODCE.md
    - Vizuální přehled: COMDIS/COMDIS_VIZUALNI_PREHLED.md
    - Modelování dokumentů: COMDIS/COMDIS_E2X_MODELCH_DOKUMENTACE.md
    - XML schéma: COMDIS/COMDIS_XML_SCHEMAT.md
  - EDISCRIPT Help:
    - Přehled: EDISCRIPT_Help/index.md
    - Přehled:
      - Basic: EDISCRIPT_Help/Basic.md
      - Introduction: EDISCRIPT_Help/Introduction.md
      - Keywords: EDISCRIPT_Help/Keywords.md
      - Logical: EDISCRIPT_Help/Logical.md
      - Navigation: EDISCRIPT_Help/Navigation.md
      - Printing: EDISCRIPT_Help/Printing.md
      - Running: EDISCRIPT_Help/Running.md
      - Sign: EDISCRIPT_Help/Sign.md
      - Variables: EDISCRIPT_Help/Variables.md
      - Window: EDISCRIPT_Help/Window.md
    - Řízení toku:
      - ACTION: EDISCRIPT_Help/ACTION.md
      - CALL: EDISCRIPT_Help/CALL.md
      - CASE: EDISCRIPT_Help/CASE.md
      - CONST: EDISCRIPT_Help/CONST.md
      - END: EDISCRIPT_Help/END.md
      - ERROR: EDISCRIPT_Help/ERROR.md
      - GOTO: EDISCRIPT_Help/GOTO.md
      - IF: EDISCRIPT_Help/IF.md
      - IFEMPTY: EDISCRIPT_Help/IFEMPTY.md
      - IFFULL: EDISCRIPT_Help/IFFULL.md
      - LASTERROR: EDISCRIPT_Help/LASTERROR.md
      - LET: EDISCRIPT_Help/LET.md
      - NEWACTION: EDISCRIPT_Help/NEWACTION.md
      - PROC: EDISCRIPT_Help/PROC.md
      - RETURN: EDISCRIPT_Help/RETURN.md
      - SWITCH: EDISCRIPT_Help/SWITCH.md
    - Systém:
      - GUID: EDISCRIPT_Help/GUID.md
      - PROGPATH: EDISCRIPT_Help/PROGPATH.md
      - READLINE: EDISCRIPT_Help/READLINE.md
      - READSEG: EDISCRIPT_Help/READSEG.md
      - READTEXT: EDISCRIPT_Help/READTEXT.md
      - REMOVESPACES: EDISCRIPT_Help/REMOVESPACES.md
      - RUN: EDISCRIPT_Help/RUN.md
      - RUNEX: EDISCRIPT_Help/RUNEX.md
      - RUNS: EDISCRIPT_Help/RUNS.md
      - RUNX: EDISCRIPT_Help/RUNX.md
      - SCRIPTNAME: EDISCRIPT_Help/SCRIPTNAME.md
      - TIME: EDISCRIPT_Help/TIME.md
      - TIMETOSTR: EDISCRIPT_Help/TIMETOSTR.md
      - TRIM: EDISCRIPT_Help/TRIM.md
      - WAIT: EDISCRIPT_Help/WAIT.md
      - WRITE: EDISCRIPT_Help/WRITE.md
      - WRITEN: EDISCRIPT_Help/WRITEN.md
    - File:
      - File: EDISCRIPT_Help/File.md
      - FILECLOSE: EDISCRIPT_Help/FILECLOSE.md
      - FILECOPY: EDISCRIPT_Help/FILECOPY.md
      - FILEDELETE: EDISCRIPT_Help/FILEDELETE.md
      - FILEEXIST: EDISCRIPT_Help/FILEEXIST.md
      - FILEEXT: EDISCRIPT_Help/FILEEXT.md
      - FILELENGTH: EDISCRIPT_Help/FILELENGTH.md
      - FILENAME: EDISCRIPT_Help/FILENAME.md
      - FILEOPEN: EDISCRIPT_Help/FILEOPEN.md
      - FILETIME: EDISCRIPT_Help/FILETIME.md
      - FILEUNIQUE: EDISCRIPT_Help/FILEUNIQUE.md
    - String:
      - STRCOPY: EDISCRIPT_Help/STRCOPY.md
      - STRFIND: EDISCRIPT_Help/STRFIND.md
      - STRFINDX: EDISCRIPT_Help/STRFINDX.md
      - String: EDISCRIPT_Help/String.md
      - STRLEN: EDISCRIPT_Help/STRLEN.md
      - STRTOTIME: EDISCRIPT_Help/STRTOTIME.md
      - STRUPPER: EDISCRIPT_Help/STRUPPER.md
    - Table:
      - Table: EDISCRIPT_Help/Table.md
      - TABLEAPPEND: EDISCRIPT_Help/TABLEAPPEND.md
      - TABLECLOSE: EDISCRIPT_Help/TABLECLOSE.md
      - TABLECREATE: EDISCRIPT_Help/TABLECREATE.md
      - TABLEDELETE: EDISCRIPT_Help/TABLEDELETE.md
      - TABLEFIND: EDISCRIPT_Help/TABLEFIND.md
      - TABLENEXT: EDISCRIPT_Help/TABLENEXT.md
      - TABLEOPEN: EDISCRIPT_Help/TABLEOPEN.md
      - TABLEOPENR: EDISCRIPT_Help/TABLEOPENR.md
      - TABLEOPENX: EDISCRIPT_Help/TABLEOPENX.md
      - TABLEOPENXR: EDISCRIPT_Help/TABLEOPENXR.md
      - TABLEREAD: EDISCRIPT_Help/TABLEREAD.md
      - TABLERECORD: EDISCRIPT_Help/TABLERECORD.md
      - TABLEUPDATE: EDISCRIPT_Help/TABLEUPDATE.md
      - TABLEWRITE: EDISCRIPT_Help/TABLEWRITE.md
    - Excel:
      - Excel: EDISCRIPT_Help/Excel.md
      - EXCELCLOSE: EDISCRIPT_Help/EXCELCLOSE.md
      - EXCELGET: EDISCRIPT_Help/EXCELGET.md
      - EXCELOPEN: EDISCRIPT_Help/EXCELOPEN.md
      - EXCELSAVE: EDISCRIPT_Help/EXCELSAVE.md
      - EXCELSET: EDISCRIPT_Help/EXCELSET.md
      - EXCELSHEET: EDISCRIPT_Help/EXCELSHEET.md
    - SQL:
      - SQL: EDISCRIPT_Help/SQL.md
      - SQLCLOSE: EDISCRIPT_Help/SQLCLOSE.md
      - SQLCONNECT: EDISCRIPT_Help/SQLCONNECT.md
      - SQLERROR: EDISCRIPT_Help/SQLERROR.md
      - SQLEXEC: EDISCRIPT_Help/SQLEXEC.md
      - SQLFETCH: EDISCRIPT_Help/SQLFETCH.md
      - SQLGET: EDISCRIPT_Help/SQLGET.md
      - SQLSELECT: EDISCRIPT_Help/SQLSELECT.md
      - SQLSET: EDISCRIPT_Help/SQLSET.md
    - Printing:
      - ORIENTATION: EDISCRIPT_Help/ORIENTATION.md
      - PAGE: EDISCRIPT_Help/PAGE.md
      - PRINT: EDISCRIPT_Help/PRINT.md
      - PRINTCLOSE: EDISCRIPT_Help/PRINTCLOSE.md
      - PRINTOPEN: EDISCRIPT_Help/PRINTOPEN.md
      - PRINTPREVIEW: EDISCRIPT_Help/PRINTPREVIEW.md
      - SETPRINTER: EDISCRIPT_Help/SETPRINTER.md
    - Grafika:
      - BARCODE: EDISCRIPT_Help/BARCODE.md
      - BITMAP: EDISCRIPT_Help/BITMAP.md
      - BRUSH: EDISCRIPT_Help/BRUSH.md
      - ELLIPSE: EDISCRIPT_Help/ELLIPSE.md
      - FONT: EDISCRIPT_Help/FONT.md
      - LABEL: EDISCRIPT_Help/LABEL.md
      - LINE: EDISCRIPT_Help/LINE.md
      - PEN: EDISCRIPT_Help/PEN.md
      - RECTANGLE: EDISCRIPT_Help/RECTANGLE.md
      - ROUNDRECT: EDISCRIPT_Help/ROUNDRECT.md
      - TEXT: EDISCRIPT_Help/TEXT.md
      - TEXTALIGN: EDISCRIPT_Help/TEXTALIGN.md
      - TEXTCOLOR: EDISCRIPT_Help/TEXTCOLOR.md
    - Dialogy:
      - BOX: EDISCRIPT_Help/BOX.md
      - BOXYESNO: EDISCRIPT_Help/BOXYESNO.md
      - OPENBOX: EDISCRIPT_Help/OPENBOX.md
      - SAVEBOX: EDISCRIPT_Help/SAVEBOX.md
    - Mail:
      - MAIL: EDISCRIPT_Help/MAIL.md
      - MAILRECEIVE: EDISCRIPT_Help/MAILRECEIVE.md
    - EDI:
      - EDIAUTACK: EDISCRIPT_Help/EDIAUTACK.md
      - EDIAUTACKEX: EDISCRIPT_Help/EDIAUTACKEX.md
      - EDICHECK: EDISCRIPT_Help/EDICHECK.md
      - EDICIPHER: EDISCRIPT_Help/EDICIPHER.md
      - EDICIPHEREX: EDISCRIPT_Help/EDICIPHEREX.md
      - EDICOUNT: EDISCRIPT_Help/EDICOUNT.md
      - EDICREATE: EDISCRIPT_Help/EDICREATE.md
      - EDIDECIPHER: EDISCRIPT_Help/EDIDECIPHER.md
      - EDIDECIPHEREX: EDISCRIPT_Help/EDIDECIPHEREX.md
      - EDIERROR: EDISCRIPT_Help/EDIERROR.md
      - EDIEXPORT: EDISCRIPT_Help/EDIEXPORT.md
      - EDIFACT: EDISCRIPT_Help/EDIFACT.md
      - EDIFATHER: EDISCRIPT_Help/EDIFATHER.md
      - EDIGET: EDISCRIPT_Help/EDIGET.md
      - EDIGETSEG: EDISCRIPT_Help/EDIGETSEG.md
      - EDIGETSEGS: EDISCRIPT_Help/EDIGETSEGS.md
      - EDIIMPEDI: EDISCRIPT_Help/EDIIMPEDI.md
      - EDIIMPORT: EDISCRIPT_Help/EDIIMPORT.md
      - EDIMESSAGE: EDISCRIPT_Help/EDIMESSAGE.md
      - EDIMSGLEN: EDISCRIPT_Help/EDIMSGLEN.md
      - EDIREAD: EDISCRIPT_Help/EDIREAD.md
      - EDIREADMSG: EDISCRIPT_Help/EDIREADMSG.md
      - EDIRESET: EDISCRIPT_Help/EDIRESET.md
      - EDIScript: EDISCRIPT_Help/EDIScript.md
      - EDISET: EDISCRIPT_Help/EDISET.md
      - EDISIGN: EDISCRIPT_Help/EDISIGN.md
      - EDISIGNEX: EDISCRIPT_Help/EDISIGNEX.md
      - EDIUNA: EDISCRIPT_Help/EDIUNA.md
      - EDIUNB: EDISCRIPT_Help/EDIUNB.md
      - EDIUNBMSG: EDISCRIPT_Help/EDIUNBMSG.md
      - EDIVERIF: EDISCRIPT_Help/EDIVERIF.md
      - EDIVERIFEX: EDISCRIPT_Help/EDIVERIFEX.md
      - EDIWRITE: EDISCRIPT_Help/EDIWRITE.md
    - X12:
      - X12: EDISCRIPT_Help/X12.md
      - X12CHECK: EDISCRIPT_Help/X12CHECK.md
      - X12COUNT: EDISCRIPT_Help/X12COUNT.md
      - X12ERROR: EDISCRIPT_Help/X12ERROR.md
      - X12EXPORT: EDISCRIPT_Help/X12EXPORT.md
      - X12FATHER: EDISCRIPT_Help/X12FATHER.md
      - X12GET: EDISCRIPT_Help/X12GET.md
      - X12IMPORT: EDISCRIPT_Help/X12IMPORT.md
      - X12MESSAGE: EDISCRIPT_Help/X12MESSAGE.md
      - X12READ: EDISCRIPT_Help/X12READ.md
      - X12RESET: EDISCRIPT_Help/X12RESET.md
      - X12SET: EDISCRIPT_Help/X12SET.md
      - X12WRITE: EDISCRIPT_Help/X12WRITE.md
    - XML:
      - XML: EDISCRIPT_Help/XML.md
      - XMLATTRGET: EDISCRIPT_Help/XMLATTRGET.md
      - XMLATTRSET: EDISCRIPT_Help/XMLATTRSET.md
      - XMLCLOSE: EDISCRIPT_Help/XMLCLOSE.md
      - XMLERROR: EDISCRIPT_Help/XMLERROR.md
      - XMLOPEN: EDISCRIPT_Help/XMLOPEN.md
      - XMLROOTTAG: EDISCRIPT_Help/XMLROOTTAG.md
      - XMLSAVE: EDISCRIPT_Help/XMLSAVE.md
      - XMLTAG: EDISCRIPT_Help/XMLTAG.md
      - XMLTAGSET: EDISCRIPT_Help/XMLTAGSET.md
      - XMLTEXTGET: EDISCRIPT_Help/XMLTEXTGET.md
      - XMLTEXTSET: EDISCRIPT_Help/XMLTEXTSET.md
    - Ostatní:
      - ;: EDISCRIPT_Help/;.md
      - BEEP: EDISCRIPT_Help/BEEP.md
      - CERTLASTDATE: EDISCRIPT_Help/CERTLASTDATE.md
      - CERTLASTDATEEX: EDISCRIPT_Help/CERTLASTDATEEX.md
      - CONVFILE: EDISCRIPT_Help/CONVFILE.md
      - CONVTEXT: EDISCRIPT_Help/CONVTEXT.md
      - COUNTER: EDISCRIPT_Help/COUNTER.md
      - EAN: EDISCRIPT_Help/EAN.md
      - FINDFILE: EDISCRIPT_Help/FINDFILE.md
      - FINDPATH: EDISCRIPT_Help/FINDPATH.md
      - GETFIELD: EDISCRIPT_Help/GETFIELD.md
      - GETITEM: EDISCRIPT_Help/GETITEM.md
      - GETTEXT: EDISCRIPT_Help/GETTEXT.md
      - INBOX: EDISCRIPT_Help/INBOX.md
      - INIREAD: EDISCRIPT_Help/INIREAD.md
      - INIWRITE: EDISCRIPT_Help/INIWRITE.md
      - NUMBER: EDISCRIPT_Help/NUMBER.md
      - RENAME: EDISCRIPT_Help/RENAME.md
      - TEXTR: EDISCRIPT_Help/TEXTR.md
      - ~TO$: EDISCRIPT_Help/~TO$.md
